version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
  save_modules:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - save_modules
  test:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - save_modules
      - run:
          name: unit test
          command: yarn test
  e2e1:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_modules
      - run:
          name: "install"
          command: "yarn install"
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3000 -timeout 1m
      - save_modules
      - run:
          name: "test"
          command: "yarn e2e"
  e2e2:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_modules
      - run:
          name: "install"
          command: "yarn install"
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait http://localhost:3000 -timeout 1m
      - save_modules
      - run:
          name: "test"
          command: "yarn e2e"
  e2e3:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_modules
      - run:
          name: "install"
          command: "yarn install"
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait http://127.0.0.1:3000 -timeout 1m
      - save_modules
      - run:
          name: "test"
          command: "yarn e2e"
  e2e:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_modules
      - run:
          name: "install"
          command: "yarn install"
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:3000 -timeout 1m
      - save_modules
      - run:
          name: "test"
          command: "yarn e2e"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - e2e
