version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:latest-browsers
    # docker:
    #   - image: circleci/node:12
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
  save_modules:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - save_modules
  test:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - save_modules
      - run:
          name: unit test
          command: yarn test
  e2e:
    executor: node
    # docker:
    #   - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_modules
      - run:
          name: "install"
          command: "yarn install"
      - save_modules
      - run:
          name: "test"
          command: "yarn e2e"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - e2e
